In [1]:
from src.convrnn_main import *
import os

In [2]:
os.environ["CUDA_VISIBLE_DEVICES"]="0"

In [3]:
data_dict = load_data("/home/jl5307/current_research/AMD_prediction/img_data/data_dictionary/longitudinal_sequential_prediction_timedelta2_data_dict_min5.pkl")
feature_dict = load_data("/home/jl5307/current_research/AMD_prediction/results/resnet101_binary/b16_lr0005_e20_detection_imagenet/extracted_feature_dict.pkl")
training_set_dict = data_dict["train_set"]
validation_set_dict = data_dict["validation_set"]
test_set_dict = data_dict["test_set"]
per_length_test_set_dict = data_dict["per_length_test_set"]

In [4]:
config = load_data("/home/jl5307/current_research/AMD_prediction/results/convlstm/testing2/convrnn_config.pkl")

In [5]:
lstm = LSTMModule(config)

In [6]:
train_eye_list = training_set_dict["eye_list"]
train_label_list = training_set_dict["label_list"]

In [7]:
i = 2
batch_size = 4

In [8]:
eye_list_batch = train_eye_list[i*batch_size:(i+1)*batch_size]
label_list_batch = train_label_list[i*batch_size:(i+1)*batch_size]
x_batch, y_batch = prepare_batch_lstm(eye_list_batch, label_list_batch, feature_dict, config)

In [9]:
y_hat = lstm(x_batch, training=True)

In [10]:
flatten_with_mask(y_batch, y_hat)

(<tf.Tensor: shape=(38,), dtype=float64, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])>,
 <tf.Tensor: shape=(38,), dtype=float32, numpy=
 array([0.49509415, 0.49203834, 0.4897685 , 0.48691553, 0.48448512,
        0.48251534, 0.4829162 , 0.4819478 , 0.47904453, 0.47713307,
        0.49402106, 0.4890907 , 0.48547325, 0.48586258, 0.48537782,
        0.48579758, 0.48636538, 0.48508242, 0.48335373, 0.48246092,
        0.49208197, 0.48158666, 0.4820729 , 0.47002628, 0.47058412,
        0.46896875, 0.47343355, 0.4737454 , 0.47757083, 0.49602196,
        0.47474846, 0.46096978, 0.46151128, 0.46412086, 0.46381018,
        0.44482738, 0.44918886, 0.45043942], dtype=float32)>)

In [11]:
flatten_with_last(y_batch, y_hat)

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.47713307, 0.48246092, 0.47757083, 0.45043942], dtype=float32)>)