In [9]:
import pickle
import numpy as np
import scipy.stats as st

In [10]:
def load_data(data_path):
    data = pickle.load(open(data_path, 'rb'))

    return data

In [3]:
load_data("/home/jl5307/current_research/AMD_prediction/results/transformer/5_fold/fold0/transformer_result_dict.pkl")

{1: {'AUC': 0.83485293, 'prediction_count': 1055},
 2: {'AUC': 0.84403527, 'prediction_count': 1055},
 3: {'AUC': 0.8490675, 'prediction_count': 1055},
 4: {'AUC': 0.8543397, 'prediction_count': 1055},
 5: {'AUC': 0.85358083, 'prediction_count': 1055},
 'entire_AUC': 0.86341196}

In [15]:
convrnn_repetition_result_dict = load_data("/home/jl5307/current_research/AMD_prediction/results/convlstm/td2/convlstm_u256_b32_e20_r10/convrnn_repetiton10_result_dict.pkl")

In [16]:
transformer_repetition_result_dict = load_data("/home/jl5307/current_research/AMD_prediction/results/transformer/td2/transformer_d256_l2_h8_b32_e30_r10/transformer_repetiton10_result_dict.pkl")

In [8]:
def get_max_validation_auc(result_dict):
    
    max_validation_auc = []
    
    for key, mydict in result_dict.items():
        max_validation_auc.append(np.max(mydict["validation_AUC"]))
        
    return max_validation_auc

In [8]:
def get_entire_auc(result_dict):
    
    max_entire_auc = []
    
    for key, mydict in result_dict.items():
        max_entire_auc.append(mydict["result"]["entire_AUC"])
        
    return max_entire_auc

In [25]:
np.mean(get_max_validation_auc(convrnn_repetition_result_dict))

0.8193218

In [26]:
np.mean(get_max_validation_auc(transformer_repetition_result_dict))

0.8297206

In [9]:
def calculate_AUC_confidence_interval(repetition_result_dict, ci=0.95):
    
    auc_list = []
    
    for key, value in repetition_result_dict.items():
        auc_list.append(value["result"]["entire_AUC"])
        
    confidence_interval = st.t.interval(ci, len(auc_list)-1, loc=np.mean(auc_list), scale=st.sem(auc_list))
    
    return np.mean(auc_list), confidence_interval

In [10]:
def calculate_AUC_confidence_interval_resnet_feature_evaluation(repetition_result_dict, ci=0.95):
    
    auc_list = []
    
    for key, value in repetition_result_dict.items():
        auc_list.append(value["entire_AUC"])
        
    confidence_interval = st.t.interval(ci, len(auc_list)-1, loc=np.mean(auc_list), scale=st.sem(auc_list))
    
    return np.mean(auc_list), confidence_interval

In [17]:
calculate_AUC_confidence_interval_resnet_feature_evaluation(resnet_feature_evaluation_repetition_result_dict)

(0.85793895, (0.8556516828480518, 0.8602262077388012))

In [18]:
calculate_AUC_confidence_interval(convrnn_repetition_result_dict)

(0.8659684, (0.862855593614109, 0.8690812187867089))

In [19]:
calculate_AUC_confidence_interval(transformer_repetition_result_dict)

(0.8668102, (0.8633381944994308, 0.8702822106977127))

In [22]:
def calculate_perlength_AUC_confidence_interval(repetition_result_dict, ci=0.95, unique_length=5):
    
    auc_dict = dict()
    auc_ci_dict = dict()
    
    for length in range(unique_length):
        auc_dict[length+1] = []
        auc_ci_dict[length+1] = []
    
    for key, value in repetition_result_dict.items():
        auc_dict[1].append(value["result"][1]["AUC"])
        auc_dict[2].append(value["result"][2]["AUC"])
        auc_dict[3].append(value["result"][3]["AUC"])
        auc_dict[4].append(value["result"][4]["AUC"])
        auc_dict[5].append(value["result"][5]["AUC"])
    
    for key, value in auc_dict.items():
        confidence_interval = st.t.interval(ci, len(value)-1, loc=np.mean(value), scale=st.sem(value))
        auc_ci_dict[key].append((np.mean(value), confidence_interval))
    
    return auc_ci_dict

In [23]:
convrnn_pl_dict = calculate_perlength_AUC_confidence_interval(convrnn_repetition_result_dict, unique_length=5)

In [24]:
convrnn_pl_dict

{1: [(0.85933524, (0.8548642782963533, 0.8638062091075164))],
 2: [(0.8648063, (0.8603183485485888, 0.8692942403338575))],
 3: [(0.8722094, (0.8675031915675536, 0.8769156679142579))],
 4: [(0.87189674, (0.8680621580558103, 0.8757313294930178))],
 5: [(0.8738432, (0.8709203773777247, 0.8767660087306738))]}

In [27]:
transformer_pl_dict = calculate_perlength_AUC_confidence_interval(transformer_repetition_result_dict, unique_length=5)

In [28]:
transformer_pl_dict

{1: [(0.85872066, (0.8519604889715202, 0.8654808314477913))],
 2: [(0.8563439, (0.8487599508031991, 0.863927899195275))],
 3: [(0.8622018, (0.8552931863829895, 0.8691104333832459))],
 4: [(0.86632806, (0.8605007652020253, 0.8721553560519419))],
 5: [(0.87288344, (0.8652557762983372, 0.8805111018297146))]}

In [ ]:
# stratified bootstrap

In [67]:
data_dict_min7 = load_data("/home/jl5307/current_research/AMD_prediction/img_data/data_dictionary/longitudinal_sequential_prediction_timedelta2_min7_data_dict_unrolled.pkl")

In [82]:
data_dict_min7["test_set"]

{'eye_list': [['54654 QUA F2 RE LS.jpg'],
  ['54654 QUA F2 RE LS.jpg', '54654 04 F2 RE LS.jpg'],
  ['54654 QUA F2 RE LS.jpg', '54654 04 F2 RE LS.jpg', '54654 06 F2 RE LS.jpg'],
  ['54654 QUA F2 RE LS.jpg',
   '54654 04 F2 RE LS.jpg',
   '54654 06 F2 RE LS.jpg',
   '54654 08 F2 RE LS.jpg'],
  ['54654 QUA F2 RE LS.jpg',
   '54654 04 F2 RE LS.jpg',
   '54654 06 F2 RE LS.jpg',
   '54654 08 F2 RE LS.jpg',
   '54654 10 F2 RE LS.jpg'],
  ['54654 QUA F2 LE LS.jpg'],
  ['54654 QUA F2 LE LS.jpg', '54654 04 F2 LE LS.jpg'],
  ['54654 QUA F2 LE LS.jpg', '54654 04 F2 LE LS.jpg', '54654 06 F2 LE LS.jpg'],
  ['54654 QUA F2 LE LS.jpg',
   '54654 04 F2 LE LS.jpg',
   '54654 06 F2 LE LS.jpg',
   '54654 08 F2 LE LS.jpg'],
  ['54654 QUA F2 LE LS.jpg',
   '54654 04 F2 LE LS.jpg',
   '54654 06 F2 LE LS.jpg',
   '54654 08 F2 LE LS.jpg',
   '54654 10 F2 LE LS.jpg'],
  ['58574 QUA F2 RE LS.jpg'],
  ['58574 QUA F2 RE LS.jpg', '58574 03 F2 RE LS.jpg'],
  ['58574 QUA F2 RE LS.jpg', '58574 03 F2 RE LS.jpg', '58574 

In [86]:
data_dict_min7["test_set"]["eye_list"]

7429

In [73]:
data_dict_min5 = load_data("/home/jl5307/current_research/AMD_prediction/img_data/data_dictionary/longitudinal_sequential_prediction_timedelta2_data_dict_min5_unrolled.pkl")

In [46]:
data_dict_td5 = load_data("/home/jl5307/current_research/AMD_prediction/img_data/data_dictionary/longitudinal_sequential_prediction_timedelta5_min7_data_dict_unrolled.pkl")

In [75]:
import matplotlib.pyplot as plt

In [47]:
def display_length_dist(data_list):
    
    elem_length_list = []
    
    for elem in data_list:
        elem_length_list.append(len(elem))
        
    return np.unique(elem_length_list, return_counts=True)

In [50]:
display_length_dist(data_dict_td5["train_set"]["eye_list"])

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 array([4370, 4346, 4269, 3973, 3602, 3183, 2839, 2463, 1980, 1148,  413,
          35,    5,    1]))

In [78]:
display_length_dist(train_eye_list_min5)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 array([5349, 4964, 4541, 4010, 3605, 3183, 2839, 2463, 1980, 1148,  413,
          35,    5,    1]))

In [148]:
display_length_dist(test_set_dict["eye_list"])

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([1152, 1089,  994,  879,  766,  707,  587,  514,  422,  232,   79,
           8]))

In [96]:
def display_label_dist(data_list):
    
    elem_label_list = []
    
    for elem in data_list:
        if np.sum(elem) > 0:
            elem_label_list.append(1)
        else:
            elem_label_list.append(0)
        
    return np.unique(elem_label_list, return_counts=True)

In [97]:
display_label_dist(train_label_list)

(array([0, 1]), array([33702,   834]))

In [149]:
display_label_dist(test_set_dict["label_list"])

(array([0, 1]), array([7237,  192]))

In [2]:
import os

In [3]:
os.listdir("/home/jl5307/current_research/AMD_prediction/results/resnet_feature_evaluation/5_fold/td2/")

['fold4', 'fold0', 'fold2', 'fold1', 'fold3']

In [20]:
def summarize_five_fold_result(fold_path, file_name):
    fold_list = os.listdir(fold_path)
    
    entire_auc_list = []
    per_length_1_auc_list = []
    per_length_2_auc_list = []
    per_length_3_auc_list = []
    per_length_4_auc_list = []
    per_length_5_auc_list = []
    
    for fold in fold_list:
        file_path = os.path.join(fold_path, fold, file_name)
        result_dict = load_data(file_path)
        
        entire_auc_list.append(result_dict["entire_AUC"])
        per_length_1_auc_list.append(result_dict[1]["AUC"])
        per_length_2_auc_list.append(result_dict[2]["AUC"])
        per_length_3_auc_list.append(result_dict[3]["AUC"])
        per_length_4_auc_list.append(result_dict[4]["AUC"])
        per_length_5_auc_list.append(result_dict[5]["AUC"])
        
    print("mean entire AUC: {}".format(np.mean(entire_auc_list)))
    print("std entire AUC: {}".format(np.std(entire_auc_list)))
    print("-----------------------------------------")
    print("mean AUC: {}".format(np.mean(per_length_1_auc_list)))
    print("std AUC: {}".format(np.std(per_length_1_auc_list)))
    print("-----------------------------------------")
    print("mean AUC: {}".format(np.mean(per_length_2_auc_list)))
    print("std AUC: {}".format(np.std(per_length_2_auc_list)))
    print("-----------------------------------------")
    print("mean AUC: {}".format(np.mean(per_length_3_auc_list)))
    print("std AUC: {}".format(np.std(per_length_3_auc_list)))
    print("-----------------------------------------")
    print("mean AUC: {}".format(np.mean(per_length_4_auc_list)))
    print("std AUC: {}".format(np.std(per_length_4_auc_list)))
    print("-----------------------------------------") 
    print("mean AUC: {}".format(np.mean(per_length_5_auc_list)))
    print("std AUC: {}".format(np.std(per_length_5_auc_list)))

In [24]:
summarize_five_fold_result("/home/jl5307/current_research/AMD_prediction/results/resnet_feature_evaluation/5_fold/td2/", 
                          "resnet_feature_evaluation_result_dict.pkl")

mean entire AUC: 0.8684965372085571
std entire AUC: 0.012570498511195183
-----------------------------------------
mean AUC: 0.8614711761474609
std AUC: 0.024129049852490425
-----------------------------------------
mean AUC: 0.8614711761474609
std AUC: 0.024129049852490425
-----------------------------------------
mean AUC: 0.8614711761474609
std AUC: 0.024129049852490425
-----------------------------------------
mean AUC: 0.8614711761474609
std AUC: 0.024129049852490425
-----------------------------------------
mean AUC: 0.8614711761474609
std AUC: 0.024129049852490425


In [25]:
summarize_five_fold_result("/home/jl5307/current_research/AMD_prediction/results/convlstm/5_fold/td2/", 
                          "convrnn_result_dict.pkl")

mean entire AUC: 0.8834463357925415
std entire AUC: 0.01693752035498619
-----------------------------------------
mean AUC: 0.8555181622505188
std AUC: 0.028697768226265907
-----------------------------------------
mean AUC: 0.8665507435798645
std AUC: 0.027521958574652672
-----------------------------------------
mean AUC: 0.8695247769355774
std AUC: 0.029217856004834175
-----------------------------------------
mean AUC: 0.8719399571418762
std AUC: 0.029042961075901985
-----------------------------------------
mean AUC: 0.8728641271591187
std AUC: 0.028935829177498817


In [26]:
summarize_five_fold_result("/home/jl5307/current_research/AMD_prediction/results/transformer/5_fold/td2/", 
                          "transformer_result_dict.pkl")

mean entire AUC: 0.8788155317306519
std entire AUC: 0.013118050992488861
-----------------------------------------
mean AUC: 0.8516707420349121
std AUC: 0.031008828431367874
-----------------------------------------
mean AUC: 0.8621859550476074
std AUC: 0.03075353056192398
-----------------------------------------
mean AUC: 0.8618216514587402
std AUC: 0.0352272167801857
-----------------------------------------
mean AUC: 0.864205002784729
std AUC: 0.03652578219771385
-----------------------------------------
mean AUC: 0.8655246496200562
std AUC: 0.0370960496366024


In [27]:
summarize_five_fold_result("/home/jl5307/current_research/AMD_prediction/results/resnet_feature_evaluation/5_fold/td5/", 
                          "resnet_feature_evaluation_result_dict.pkl")

mean entire AUC: 0.8616607785224915
std entire AUC: 0.02297462522983551
-----------------------------------------
mean AUC: 0.8618680834770203
std AUC: 0.022679423913359642
-----------------------------------------
mean AUC: 0.8618680834770203
std AUC: 0.022679423913359642
-----------------------------------------
mean AUC: 0.8618680834770203
std AUC: 0.022679423913359642
-----------------------------------------
mean AUC: 0.8618680834770203
std AUC: 0.022679423913359642
-----------------------------------------
mean AUC: 0.8618680834770203
std AUC: 0.022679423913359642


In [28]:
summarize_five_fold_result("/home/jl5307/current_research/AMD_prediction/results/convlstm/5_fold/td5/", 
                          "convrnn_result_dict.pkl")

mean entire AUC: 0.8785545229911804
std entire AUC: 0.019553732126951218
-----------------------------------------
mean AUC: 0.8556297421455383
std AUC: 0.03066219761967659
-----------------------------------------
mean AUC: 0.8667978048324585
std AUC: 0.02830367349088192
-----------------------------------------
mean AUC: 0.8692710995674133
std AUC: 0.031112756580114365
-----------------------------------------
mean AUC: 0.8716737031936646
std AUC: 0.030704336240887642
-----------------------------------------
mean AUC: 0.8729132413864136
std AUC: 0.029787426814436913


In [29]:
summarize_five_fold_result("/home/jl5307/current_research/AMD_prediction/results/transformer/5_fold/td5/", 
                          "transformer_result_dict.pkl")

mean entire AUC: 0.8725025057792664
std entire AUC: 0.020482223480939865
-----------------------------------------
mean AUC: 0.8458773493766785
std AUC: 0.02900003269314766
-----------------------------------------
mean AUC: 0.8614540100097656
std AUC: 0.029027031734585762
-----------------------------------------
mean AUC: 0.8634124994277954
std AUC: 0.03170520439743996
-----------------------------------------
mean AUC: 0.8657819032669067
std AUC: 0.02838093787431717
-----------------------------------------
mean AUC: 0.8677722811698914
std AUC: 0.028571587055921555
